version: "3"
services:

  subscription-db:
    image: postgres:11
    container_name: subscription-db
    restart: always
    networks:
      - subscription-network
    environment:
      - POSTGRES_DB=subscription-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432

  subscription_rabbit:
    image: rabbitmq:3-management
    container_name: subscription_rabbit
    hostname: subscription_rabbit
    networks:
      - subscription-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  subscription:
    build: './subscription'
    container_name: subscription
    depends_on:
      - subscription-db
      - subscription_rabbit
    networks:
      - subscription-network
    environment:
      - PORT=8081
      #- API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=subscription-db
      - DB_NAME=subscription-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=subscription_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
    ports:
      - 8081:8081

networks:
  subscription-network:
    driver: bridge