version: "3"
services:

  subscription-db:
    image: postgres:11
    container_name: subscription-db
    restart: always
    networks:
      - subscription-network
    environment:
      - POSTGRES_DB=subscription-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  subscription_rabbit:
    image: rabbitmq:3-management
    container_name: subscription_rabbit
    hostname: subscription_rabbit
    networks:
      - subscription-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  subscription-api:
    build: './subscription-api'
    container_name: subscription-api
    depends_on:
      - subscription-db
      - subscription_rabbit
    networks:
      - subscription-network
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - PORT=8081
      - DB_PORT=5432
      - DB_HOST=subscription-db
      - DB_NAME=subscription-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - RABBIT_MQ_HOST=subscription_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
    ports:
      - 8081:8081

  consumer-api:
    build: './consumer-api'
    container_name: consumer-api
    depends_on:
      - subscription-db
      - subscription_rabbit
    networks:
      - subscription-network
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - PORT=8082
      - RABBIT_MQ_HOST=subscription_rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
    ports:
      - 8082:8082

networks:
  subscription-network:
    driver: bridge

