--lembrar que aqui as linhas não podem ser quebradas pq da problema no Hibernate.

INSERT INTO SUBSCRIPTION_TABLE (ID, NAME, STATUS, CREATED_AT) VALUES (0, 'MARCOS', true, CURRENT_TIMESTAMP);
INSERT INTO SUBSCRIPTION_TABLE (ID, NAME, STATUS, CREATED_AT) VALUES (1, 'PREDO', false, CURRENT_TIMESTAMP);
