--lembrar que aqui as linhas não podem ser quebradas pq da problema no Hibernate.

INSERT INTO SUBSCRIPTION_TABLE (ID, NAME, STATUS, CREATED_AT) VALUES (0, 'MARCOS', 'ATIVO', 1000, 1000, CURRENT_TIMESTAMP);
INSERT INTO SUBSCRIPTION_TABLE (ID, NAME, STATUS, CREATED_AT) VALUES (1, 'PREDO', 'CANCELADO', 1001, 1001, CURRENT_TIMESTAMP);
