server:
  port: 8082

spring:

  application:
    name: consumer-api

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:
  rabbit:
    exchange:
      subscription-api: subscription.topic

    routingKey:
      consumer-update: consumer-update.routingKey

    queue:
      consumer-update: consumer-update.queue
